version: '3.2'

services:
  nodejs:
    build: .
    image: nodejs
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    environment:
      # MONGODB_URL: mongodb+srv://0606bach:d2XUdXtmQXbZYyOI@cluster0.vc1gtc4.mongodb.net/checkin
      MONGODB_URL: mongodb://mongo:27017/checkin
    networks:
      - my-network
  mongo:
    image: mongo
    networks:
      - my-network     
    ports:
    - '27017:27017'
    volumes:
    - /data/db:/data/db
  nginx:
    build: 
      dockerfile: Dockerfile
      context: ./nginx
    image: nginx
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    depends_on:
      - nodejs 
    environment:
      - COMPANY_IP=172.24.0.1
    restart: unless-stopped
    networks:
      - my-network
networks:
  my-network:
    driver: bridge
volumes:
  mongodb: