version: '3.2'

services:
  nodejs:
    build: .
    image: nodejs
    ports:
      - '3000:3000'
    environment:
      MONGODB_URL: ${MONGODB_URL}
      SLACK_TOKEN: ${SLACK_TOKEN}
      CHANNEL_ID: ${CHANNEL_ID}
    restart: unless-stopped
    networks:
      - my-network
  nginx:
    build: 
      dockerfile: Dockerfile
      context: ./nginx
    image: nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - nodejs 
    environment:
      - COMPANY_IP=${COMPANY_IP}
    restart: unless-stopped
    networks:
      - my-network
networks:
  my-network:
    driver: bridge
volumes:
  mongodb:
