const schedule = [
  { code: '2S', object: { time: 'morning', day: 'monday' } },
  { code: '2C', object: { time: 'afternoon', day: 'monday' } },
  { code: '2F', object: { time: 'full', day: 'monday' } },
  { code: '3S', object: { time: 'morning', day: 'tuesday' } },
  { code: '3C', object: { time: 'afternoon', day: 'tuesday' } },
  { code: '3F', object: { time: 'full', day: 'tuesday' } },
  { code: '4S', object: { time: 'morning', day: 'wednesday' } },
  { code: '4C', object: { time: 'afternoon', day: 'wednesday' } },
  { code: '4F', object: { time: 'full', day: 'wednesday' } },
  { code: '5S', object: { time: 'morning', day: 'thursday' } },
  { code: '5C', object: { time: 'afternoon', day: 'thursday' } },
  { code: '5F', object: { time: 'full', day: 'thursday' } },
  { code: '6S', object: { time: 'morning', day: 'friday' } },
  { code: '6C', object: { time: 'afternoon', day: 'friday' } },
  { code: '6F', object: { time: 'full', day: 'friday' } },
  { code: '7S', object: { time: 'morning', day: 'saturday' } },
  { code: '7C', object: { time: 'afternoon', day: 'saturday' } },
  { code: '7F', object: { time: 'full', day: 'saturday' } },
  { code: '8S', object: { time: 'morning', day: 'sunday' } },
  { code: '8C', object: { time: 'afternoon', day: 'sunday' } },
  { code: '8F', object: { time: 'full', day: 'sunday' } },
];
module.exports = schedule;
